name: Tencent Tracking Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'  # runs every 10 minutes

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Chromium and Chromedriver via snap
        run: |
          sudo snap install chromium
          sudo ln -s /snap/bin/chromium.chromedriver /usr/bin/chromedriver || true
          sudo ln -s /snap/bin/chromium /usr/bin/chromium || true

      - name: Run the bot
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python manhua_bot.py
