name: Tencent Tracking Bot

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Chromium
        run: |
          sudo apt update
          sudo apt install -y chromium-browser

      - name: Ensure chromedriver is accessible
        run: |
          if [ ! -f /usr/bin/chromedriver ] || [ "$(readlink -f /usr/bin/chromedriver)" != "$(readlink -f /usr/lib/chromium-browser/chromedriver)" ]; then
            sudo cp /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver
          fi

      - name: Run Tencent Tracking Bot
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python manhua_bot.py

      - name: Commit and push updated series.json
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add series.json
          git diff --cached --quiet || git commit -m "Update series.json [bot]"
          git push
