name: Tencent Tracking Bot

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Chrome & Chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          if [ ! -f /usr/bin/chromedriver ] || [ "$(readlink -f /usr/bin/chromedriver)" != "$(readlink -f /usr/lib/chromium-browser/chromedriver)" ]; then
            sudo cp /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver
          fi

      - name: Run bot
        run: python manhua_bot.py
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
